module.exports = {
  assign: require('./assign'),
  clone: require('./clone'),
  filter: require('./filter'),
  flow: require('./flow'),
  get: require('./get'),
  identity: require('./identity'),
  isObject: require('./isObject'),
  join: require('./join'),
  keys: require('./keys'),
  map: require('./map'),
  mapValues: require('./mapValues'),
  negate: require('./negate'),
  reduce: require('./reduce'),
  reject: require('./reject'),
  set: require('./set'),
  slice: require('./slice'),
  sortBy: require('./sortBy'),
  split: require('./split'),
  values: require('./values')
}
