#!/bin/sh

if [[ `git status --porcelain README.md` ]]; then
  echo "(docs) Generating new README.md"
  git add README.md && git commit -m 'docs: Generate README' --no-verify
else
  echo "(docs) Nothing further"
fi
