#!/bin/sh

if [[ `git status --porcelain README.md` ]]; then
  echo "(docs) Generating new README.md"
  git add README.md && git commit -m 'docs: Generate README'
  git push origin "$(git branch | grep \* | cut -d ' ' -f2)" --no-verify
else
  echo "Nothing further"
fi
